name: deploy-to-prod
on: [push]
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::784714698706:role/github-action-kylewiliams.dev
        role-session-name: sync-gh-to-s3
        aws-region: us-east-2
    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync ./src s3://kylewilliams.dev --delete --follow-symlinks