name: deploy-to-prod
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: kylewilliams.dev
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      S3_SOURCE_DIR: 'src'
    steps:
      - uses: actions/checkout@v3

      - name: S3/CloudFront Deploy
        uses: staevs/s3-deploy-action@v1.2.2
        if: success()
        with:
          args: --follow-symlinks --delete --no-progress